version: '3'

services:

  nginx-web:
    image: nginx
    labels:
        com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy: "true"
    container_name: nginx-web
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./docker/letsencrypt/shared/conf.d:/etc/nginx/conf.d
      - ./docker/letsencrypt/shared/vhost.d:/etc/nginx/vhost.d
      - ./docker/letsencrypt/shared/html:/usr/share/nginx/html
      - ./docker/letsencrypt/shared/certs:/etc/nginx/certs:ro
      - ./docker/letsencrypt/shared/htpasswd:/etc/nginx/htpasswd:ro

  nginx-gen:
    image: jwilder/docker-gen
    command: -notify-sighup nginx-web -watch -wait 5s:30s /etc/docker-gen/templates/nginx.tmpl /etc/nginx/conf.d/default.conf
    container_name: nginx-gen
    restart: always
    volumes:
      - ./docker/letsencrypt/shared/conf.d:/etc/nginx/conf.d
      - ./docker/letsencrypt/shared/vhost.d:/etc/nginx/vhost.d
      - ./docker/letsencrypt/shared/html:/usr/share/nginx/html
      - ./docker/letsencrypt/shared/certs:/etc/nginx/certs:ro
      - ./docker/letsencrypt/shared/htpasswd:/etc/nginx/htpasswd:ro
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./docker/letsencrypt/nginx.tmpl:/etc/docker-gen/templates/nginx.tmpl:ro

  nginx-letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: ${LETS_ENCRYPT:-nginx-letsencrypt}
    restart: always
    volumes:
      - ./docker/letsencrypt/shared/conf.d:/etc/nginx/conf.d
      - ./docker/letsencrypt/shared/vhost.d:/etc/nginx/vhost.d
      - ./docker/letsencrypt/shared/html:/usr/share/nginx/html
      - ./docker/letsencrypt/shared/certs:/etc/nginx/certs:rw
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      NGINX_DOCKER_GEN_CONTAINER: nginx-gen
      NGINX_PROXY_CONTAINER: nginx-web

  nginx:
    image: nginx:1.11
    depends_on:
      - php
    volumes:
      - ./:/var/www/html:ro
      - ./docker/nginx/config/grosgary-prod.conf:/etc/nginx/conf.d/default.conf:ro
    environment:
      - VIRTUAL_HOST=www.grosgarycollection.com
      - VIRTUAL_NETWORK=nginx-proxy
      - VIRTUAL_PORT=80
      - LETSENCRYPT_HOST=www.grosgarycollection.com
      - LETSENCRYPT_EMAIL=david.buros@gmail.com

  php:
    build: ./docker/php
    working_dir: /var/www/html
    environment:
      - XDEBUG_CONFIG="remote_host=10.254.254.254"
      - PHP_IDE_CONFIG="serverName=local.warnerbros.fr"
    depends_on:
      - mysql
    expose:
      - 9000
    volumes:
      - ./:/var/www/html:delegated

  mysql:
    image: mysql:5.6
    environment:
      MYSQL_DATABASE: grosgary_dev
      MYSQL_USER: grosgary
      MYSQL_PASSWORD: grosgary
      MYSQL_ROOT_PASSWORD: grosgary
    ports:
      - 3306:3306

  mailhog:
    image: mailhog/mailhog:latest
    ports:
      - 8025:8025

  composer:
    image: composer:1.4
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html:delegated