version: '3'

services:

  nginx:
    image: nginx:1.11
    depends_on:
      - php
    ports:
      - 80:80
    networks:
      - front-tier
    volumes:
      - ./:/var/www/html:ro
      - ./docker/nginx/config/grosgary.conf:/etc/nginx/conf.d/default.conf:ro

  php:
    build: ./docker/php
    working_dir: /var/www/html
    environment:
      - XDEBUG_CONFIG="remote_host=10.254.254.254"
      - PHP_IDE_CONFIG="serverName=grosgary"
    depends_on:
      - mysql
    expose:
      - 9000
    networks:
      - front-tier
      - back-tier
    volumes:
      - ./:/var/www/html:delegated

  mysql:
    image: mysql:5.6
    environment:
      MYSQL_DATABASE: grosgary_dev
      MYSQL_USER: grosgary
      MYSQL_PASSWORD: grosgary
      MYSQL_ROOT_PASSWORD: grosgary
    ports:
      - 3306:3306
    networks:
      - back-tier

  mailhog:
    image: mailhog/mailhog:latest
    ports:
      - 8025:8025
    networks:
      - front-tier

  composer:
    image: composer:1.4
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html:delegated

networks:
  front-tier:
    driver: bridge
  back-tier:
    driver: bridge